name: Feature Request
description: Submit a feature request
title: "[Feat]: "
labels: ["feature"]
assignees:
  - blackboardd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest!
  - type: input
    id: contact
    attributes:
      label: Contact
      description: How do we get in touch?
      placeholder: null@null.com
    validations:
      required: false
  - type: textarea
    id: your-idea
    attributes:
      label: Share your idea
      description: What's on your mind?
      placeholder: Explain
      value: ""
    validations:
      required: true